<script type="text/template" id="push_dialog_tpl" data-style="home_1" data-title="<?php echo T('push_to_home_index');?>" data-crop-url="<?php echo spUrl('share','crop_category_hot_share');?>" data-fetch-url="<?php echo spUrl('share','find_category_hot_share');?>">
 {{#data}} 
	<div class="category-bd">
		<a href="javascript:void(0);" id="link_home_1" data-action="switchPushStyle" data-params="home_1" class="selected"><?php echo T('style_1');?></a> | 
		<a href="javascript:void(0);" id="link_home_2" data-action="switchPushStyle" data-params="home_2"><?php echo T('style_2');?></a> | 
		<a href="javascript:void(0);" id="link_home_3" data-action="switchPushStyle" data-params="home_3"><?php echo T('style_3');?></a>
	</div>
    <div class="category-bd push_style" id="push_home_1">
    	<div class="category-hot-132-274 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="1,132:274">{{#s1.image_path}}<img src="<?php echo base_url()?>{{s1.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s1.image_path}}{{^s1.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s1.image_path}}</a></div>
		<div class="category-hot-132-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="2,132:132">{{#s2.image_path}}<img src="<?php echo base_url()?>{{s2.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s2.image_path}}{{^s2.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s2.image_path}}</a></div>
    	<div class="category-hot-132-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="3,132:132">{{#s3.image_path}}<img src="<?php echo base_url()?>{{s3.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s3.image_path}}{{^s3.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s3.image_path}}</a></div>
    	<div class="category-hot-274-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="4,274:132">{{#s4.image_path}}<img src="<?php echo base_url()?>{{s4.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s4.image_path}}{{^s4.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s4.image_path}}</a></div>
    	<div class="category-hot-274-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="5,274:132">{{#s5.image_path}}<img src="<?php echo base_url()?>{{s5.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s5.image_path}}{{^s5.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s5.image_path}}</a></div>
    	<div class="category-hot-132-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="6,132:132">{{#s6.image_path}}<img src="<?php echo base_url()?>{{s6.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s6.image_path}}{{^s6.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s6.image_path}}</a></div>
    	<div class="category-hot-132-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="7,132:132">{{#s7.image_path}}<img src="<?php echo base_url()?>{{s7.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s7.image_path}}{{^s7.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s7.image_path}}</a></div>
	</div>
    <div class="category-bd push_style hide" id="push_home_2">
    	<div class="category-hot-167-274 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="1,167:274">{{#s1.image_path}}<img src="<?php echo base_url()?>{{s1.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s1.image_path}}{{^s1.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s1.image_path}}</a></div>
		<div class="category-hot-167-274 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="2,167:274">{{#s2.image_path}}<img src="<?php echo base_url()?>{{s2.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s2.image_path}}{{^s2.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s2.image_path}}</a></div>
    	<div class="category-hot-344-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="3,344:132">{{#s3.image_path}}<img src="<?php echo base_url()?>{{s3.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s3.image_path}}{{^s3.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s3.image_path}}</a></div>
    	<div class="category-hot-344-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="4,344:132">{{#s4.image_path}}<img src="<?php echo base_url()?>{{s4.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s4.image_path}}{{^s4.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s4.image_path}}</a></div>
	</div>
    <div class="category-bd push_style hide" id="push_home_3">
    	<div class="category-hot-167-274 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="1,167:274">{{#s1.image_path}}<img src="<?php echo base_url()?>{{s1.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s1.image_path}}{{^s1.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s1.image_path}}</a></div>
		<div class="category-hot-167-274 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="2,167:274">{{#s2.image_path}}<img src="<?php echo base_url()?>{{s2.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s2.image_path}}{{^s2.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 120px;">{{/s2.image_path}}</a></div>
    	<div class="category-hot-167-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="3,167:132">{{#s3.image_path}}<img src="<?php echo base_url()?>{{s3.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s3.image_path}}{{^s3.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s3.image_path}}</a></div>
    	<div class="category-hot-167-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="4,167:132">{{#s4.image_path}}<img src="<?php echo base_url()?>{{s4.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s4.image_path}}{{^s4.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s4.image_path}}</a></div>
    	<div class="category-hot-167-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="5,167:132">{{#s5.image_path}}<img src="<?php echo base_url()?>{{s5.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s5.image_path}}{{^s5.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s5.image_path}}</a></div>
    	<div class="category-hot-167-132 text_c"><a href="javascript:void(0);" data-action="openCrop" data-params="6,167:132">{{#s6.image_path}}<img src="<?php echo base_url()?>{{s6.image_path}}_home.jpg?{{rand}}" onerror="this.src='<?php echo base_url()?>assets/img/pin_button.png';"/>{{/s6.image_path}}{{^s6.image_path}}<img src="<?php echo base_url()?>assets/img/pin_button.png" style="margin-top: 50px;">{{/s6.image_path}}</a></div>
	</div>
    <br/>
 {{/data}} 
</script>